name = "HLSL"
grammar = "hlsl"
path_suffixes = ["hlsl", "hlsli", "fx", "fxh", "ush", "usf"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
